name: Build

on: [workflow_dispatch]

jobs:
  build_docker:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push x86_64
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: kekcheburec2/mv-extractor:dev-amd64
          cache-from: type=registry,ref=kekcheburec2/mv-extractor:buildcache-amd64
          cache-to: type=registry,ref=kekcheburec2/mv-extractor:buildcache-amd64,mode=max

      - name: Build and push ARM
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: kekcheburec2/mv-extractor:dev-aarch64
          cache-from: type=registry,ref=kekcheburec2/mv-extractor:buildcache-aarch64
          cache-to: type=registry,ref=kekcheburec2/mv-extractor:buildcache-aarch64,mode=max

  build_wheels_x86_64:
    name: Build x86_64 wheels
    runs-on: ubuntu-latest
    needs: build_docker

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_PLATFORM: linux
          CIBW_BUILD: cp310-manylinux_x86_64
          CIBW_SKIP: pp*
          CIBW_ARCHS: x86_64
          CIBW_MANYLINUX_X86_64_IMAGE: kekcheburec2/mv-extractor:dev-amd64
          CIBW_BUILD_FRONTEND: build
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-x86_64
          path: ./wheelhouse/*.whl

  build_wheels_arm64:
    name: Build ARM64 wheels
    runs-on: ubuntu-latest
    needs: build_docker

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_PLATFORM: linux
          CIBW_BUILD: cp310-manylinux_aarch64
          CIBW_SKIP: pp*
          CIBW_ARCHS: aarch64
          CIBW_MANYLINUX_AARCH64_IMAGE: kekcheburec2/mv-extractor:dev-aarch64
          CIBW_BUILD_FRONTEND: build
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-arm64
          path: ./wheelhouse/*.whl
